LatinIME: Fix NPE in getKeyboardThemeName
* Other components like KeyboardBuilder use this method and are not
  guaranteed to pass a valid themeId (e.g. because it requests one of
  the removed keyboard themes)
* In those cases lookup the default keyboard with DEFAULT_THEME_ID
  and use that to return the theme name

Fixes: Spellchecker not doing its' job

Fixes:
java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.android.inputmethod.keyboard.KeyboardTheme.mThemeName' on a null object reference
  at com.android.inputmethod.keyboard.KeyboardTheme.getKeyboardThemeName(KeyboardTheme.java:123)

Change-Id: Ib7b7b516c7747700b4e05073b806814d9da95238